# .gitlab-ci.yml for USGS SAS deployment
#
# Reference:
#   - https://docs.gitlab.com/ee/ci/yaml/
#
# CI Variables:
#   DEPLOY_TRIGGER_REF
#     Set on the individual deployment jobs below. This is the branch name to trigger on the deployment pipeline.
#
#   DEPLOY_TRIGGER_TOKEN
#     Specified external to this file as a CI variable.
#
#   DEPLOY_TRIGGER_URL
#     Specified external to this file as a CI variable.
#
include:
  - project: 'sas/ops/ci-pipeline/gitlab-ci-pipeline'
    file: '/common-vars.yml'
  - project: 'sas/ops/ci-pipeline/gitlab-ci-pipeline'
    file: '/deploy/api_trigger.yml'

stages:
  - build
  - deploy

npm_build:
  stage: build
  # Use an internal registry for node
  # This variable is from the included '/common-vars.yml'
  image: ${SAS_IMAGE_NODE}:10.15
  tags:
    - docker
  script:
    - export PATH=${PWD}/node_modules/.bin:${PATH}
    - npm install
    - npm install react-scripts@1.1.1 -g --silent
    - npm run build
  artifacts:
    paths:
      - build

trigger_deploy_development:
  extends: .deploy_trigger
  stage: deploy
  variables:
    # Pass along the build artifact information with the trigger
    ARTIFACT_JOB: npm_build
    # Trigger the 'development' branch on the deploy pipeline
    DEPLOY_TRIGGER_REF: development
  only:
    refs:
      - development

trigger_deploy_master:
  extends: .deploy_trigger
  stage: deploy
  variables:
    # Pass along the build artifact information with the trigger
    ARTIFACT_JOB: npm_build
    # Trigger the 'master' branch on the deploy pipeline
    DEPLOY_TRIGGER_REF: master
  only:
    refs:
      - master
